language: php

env:
  global:
    - CHECK_CODE_STYLE="no"
    - COMPOSER_FLAGS=""
    - COMPOSER_MEMORY_LIMIT=-1
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - SYMFONY_VERSION=""

matrix:
  fast_finish: true
  include:
    # oldest supported versions
    - php: 7.2
      env:
        - SYMFONY_VERSION="3.4.*"
        - COMPOSER_FLAGS="--prefer-lowest"
        - SYMFONY_DEPRECATIONS_HELPER=weak_vendors
        - SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT=1

    - php: 7.3
      env:
        - SYMFONY_VERSION="4.4.*"

    - php: 7.4
      env:
        - SYMFONY_VERSION="5.1.*"
        - CHECK_CODE_STYLE="yes"

    # most recent versions:
    - php: 8.0
      env:
        - SYMFONY_VERSION="5.1.*"

    # bleeding edge (unreleased dev versions where failures are allowed):
    - php: nightly # PHP 8.1
      env: SYMFONY_VERSION="5.2.*"

  allow_failures:
    - env: SYMFONY_VERSION="5.3.*"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/symfony-bridge/.phpunit

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 'nightly' ]]; then phpenv config-rm xdebug.ini; fi;
  - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [[ "$CHECK_CODE_STYLE" != "yes" ]]; then composer remove "friendsofphp/php-cs-fixer" --no-update --no-interaction --dev; fi;

install:
  - |
    # Set composer's platform to php 7.4 if we're on php 8 & use dev version of phpunit-bridge (which ignores platform reqs)
    echo $TRAVIS_PHP_VERSION
    if [[ $TRAVIS_PHP_VERSION = 'nightly' ]]; then
      echo "Set composer's platform to php 7.4"
      composer config platform.php 7.4.99
      composer require "symfony/phpunit-bridge:5.1.x-dev" --no-update --no-interaction --dev
    fi
  - composer update --prefer-dist --no-interaction --optimize-autoloader --prefer-stable --no-progress $COMPOSER_FLAGS

script:
  - bin/simple-phpunit
  - if [[ "$CHECK_CODE_STYLE" == "yes" ]]; then PHP_CS_FIXER_FUTURE_MODE=1 bin/php-cs-fixer fix --config=.php_cs --dry-run --no-interaction --diff; fi;
