name: Continuous Integration

on: [push]

jobs:
    cs:
        name: Code Style
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  coverage: xdebug
            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Install Dependencies
              run: composer install --no-progress
            - name: Run php-cs-fixture
              env:
                  PHP_CS_FIXER_FUTURE_MODE: 1
              run: bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run --no-interaction --diff

    phpunit:
        name: Unit Tests
        runs-on: ubuntu-20.04
        env:
            COMPOSER_MEMORY_LIMIT: "-1"
        strategy:
            matrix:
                include:
                    # oldest supported versions
                    - php: 7.2
                      composer_flags: "--prefer-lowest"
                      cs_fixer_config: "1.3.*"
                      symfony_phpunit_remove_return_typehint: 1
                    - php: 7.3
                      symfony_version: "4.4.*"
                    - php: 7.4
                      symfony_version: "5.1.*"
                    - php: 7.4
                      symfony_version: 5.2.*
                    # most recent versions
                    - php: 8.0
                      symfony_version: 5.3.*
                    - php: 8.0
                      symfony_version: 5.4.*
                    - php: 8.0
                      symfony_version: 6.0.*
                    - php: 8.1
                    - php: 8.2
                    - php: 8.3
                      symfony_version: 7.0.*
            fail-fast: false
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring
                  coverage: xdebug
            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Install Symfony ${{ matrix.symfony_version }}
              run: composer require "symfony/framework-bundle:${{ matrix.symfony_version }}" --no-update
              if: matrix.symfony_version != ''
            - name: Downgrade php-cs-fixer
              run: composer require "m6web/php-cs-fixer-config:${{ matrix.cs_fixer_config }}" --no-update
              if: matrix.cs_fixer_config != ''
            - name: Install Dependencies
              run: composer update --prefer-dist --no-interaction --optimize-autoloader --prefer-stable --no-progress $COMPOSER_FLAGS
              env:
                  COMPOSER_FLAGS: ${{ matrix.composer_flags }}
            - name: Run PHPUnit
              run: bin/simple-phpunit
              env:
                  SYMFONY_DEPRECATIONS_HELPER: weak
                  SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT: ${{ matrix.symfony_phpunit_remove_return_typehint }}
